In [4]:
import random
import numpy as np

In [24]:
l1=np.array([0]*(13*4*2+4-4)+[1]*4)

In [25]:
l1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [28]:
np.random.shuffle(l1)

In [29]:
l1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
i=0
number_dict=dict()
while i<10000:
    i=i+1
    np.random.shuffle(l1)
    #print(l1)
    l2=np.split(l1,6)
    #print(l2)
    l3=np.sum(l2,axis=1)
    sum_list=str(sorted(list(l3),reverse=True)[0:3])
    if sum_list not in number_dict.keys():
        v=0
        number_dict.update({sum_list:v})
    else:
        v=number_dict[sum_list]
        v=v+1
        number_dict.update({sum_list:v})

In [45]:
number_dict

{'[2, 1, 1]': 5530,
 '[3, 1, 0]': 768,
 '[1, 1, 1]': 2991,
 '[2, 2, 0]': 672,
 '[4, 0, 0]': 34}

In [36]:
l3

array([1, 1, 0, 1, 1, 0])